INSERT INTO projeto (COD_FUNCIONARIO_RESP, NOME_PROJETO, COD_CLIENTE, CONTATO_EMPRESA, COD_PROGRAMADOR_CHEFE, OBSERVACOES, COD_STATUS_SOFTWARE, NOTIF_CLIENTE, NOTIF_PROGRAMADOR, DATA_INICIAL, DATA_FINAL, NUM_DEPENDENCIAS, COD_ANALISTA_RESP, created_at, updated_at) VALUES

(4, 'INFOTECH SAC - SOFTWARE PRINCIPAL', 32, 'PAULO / MONICK', 4, "testes", 1, 'N', 'S', '2004-01-01', NULL, NULL, 12, NOW(), NOW()),
(86, 'INFOTECH SAC - TROPICAL EMPILHADEIRAS', 15, 'SR. RICARTE', 50, "testes", 2, 'N', 'S', '2016-02-01', NULL, NULL, 50, NOW(), NOW()),
(5, 'INFOTECH RAD - SMART SOLUÇÕES', 26, 'CRISTINA / PEDRO', 4, "testes", 1, 'N', 'S', '2016-02-01', NULL, NULL, 23, NOW(), NOW()),
(39, 'INFOTECH SAC - COMETEC INSPEÇÕES PORTUÁRIAS', 30, 'OZENI / ADRIANO / MARISE', 39, "testes", 4, 'N', 'S', '2016-02-01', NULL, NULL, 45, NOW(), NOW());